### ISSUE TITLE
Unable to compile on S3, as not finding littlefs submodule, as not imported using component manager.

### ISSUE THREAD

**Issue by wreyford** [joltwallet/esp_littlefs#50]
When building a project for ESP32 S3,  in Visual Studio Code Insiders on Windows 10, the component manager fetches the joltwallet__littlefs component, and adds it to the /managed_components folder.
The folder structure is correct, but for /littlefs ... see image below.
It appears not to import the submodule, so the /littlefs folder is empty...

![empty_littlefs](https://user-images.githubusercontent.com/50998190/146570760-5fdca52c-105b-411c-8347-db2588848b6d.jpg)

So the build fails as it cannot find 
```
#include "littlefs/lfs.h"
```
Is there something I must add to .vscode settings.jason.
I have added:
```
"idf.enableIdfComponentManager": true,
```
Build error log follows

```
> Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .. <

-- Found Git: C:/esp/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
Processing 3 dependencies:
[1/3] idf (4.4.0)
[2/3] joltwallet/littlefs (1.0.0)
[3/3] lvgl/lvgl (8.1.0)
CMake Error at C:/esp/esp-idf/tools/cmake/build.cmake:200 (message):
  Failed to resolve component 'esp_littlefs'.
Call Stack (most recent call first):
  C:/esp/esp-idf/tools/cmake/build.cmake:226 (__build_resolve_and_add_req)
  C:/esp/esp-idf/tools/cmake/build.cmake:512 (__build_expand_requirements)
  C:/esp/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:6 (project)
```

Please, any help will be appreciated.

**Comment by BrianPugh** [comment]
Hmmm, so i've never actually used the component manager before, but downloading the archive directly from the website also has the missing files, so something is definitely not checking out the submodule somewhere. I'll see if I can debug this a lil.

**Comment by wreyford** [comment]
Thx

**Comment by BrianPugh** [comment]
alright @wreyford , I think I fixed it. I updated the CI so that it recursively checks out submodule when building the tarball for the IDF component manager. I also bumped the version so there's now v1.0.1.  I downloaded the tar from the official website and the files are there now, so hopefully this fixes your issue (lemme know!). Thanks for noticing and reporting this.

**Comment by wreyford** [comment]
Thanks for the prompt reply @BrianPugh , unfortunately, still unable to compile.

```
> Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .. <

-- Found Git: C:/esp/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
Processing 3 dependencies:
[1/3] idf (4.4.0)
[2/3] joltwallet/littlefs (1.0.1)
[3/3] lvgl/lvgl (8.1.0)
CMake Error at C:/esp/esp-idf/tools/cmake/build.cmake:200 (message):
  Failed to resolve component 'esp_littlefs'.
Call Stack (most recent call first):
  C:/esp/esp-idf/tools/cmake/build.cmake:226 (__build_resolve_and_add_req)
  C:/esp/esp-idf/tools/cmake/build.cmake:512 (__build_expand_requirements)
  C:/esp/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "C:/ESP32/Projects/loadassist-s3/build/CMakeFiles/CMakeOutput.log".
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .." terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```
The files appear to be in place, but perhaps its a missing #define somewhere for ESP32S3 that is resulting in it fialing to find the component in CMake.

Attached log file.
[CMakeOutput.log](https://github.com/joltwallet/esp_littlefs/files/7737074/CMakeOutput.log)

**Comment by wreyford** [comment]
Perhaps altering from line 19 of esp_littlefs.c
```
#include <sys/param.h>
#if CONFIG_IDF_TARGET_ESP32C3
#include "esp32c3/rom/spi_flash.h"
#elif CONFIG_IDF_TARGET_ESP32S2
#include "esp32s2/rom/spi_flash.h"
#elif __has_include("esp32/rom/spi_flash.h")
#include "esp32/rom/spi_flash.h" //IDF 4
#else
#include "rom/spi_flash.h" //IDF 3
#endif
#include "esp_system.h"

#include "esp_littlefs.h"
#include "littlefs_api.h"
```
to:
```
#include <sys/param.h>
#if CONFIG_IDF_TARGET_ESP32S3
#include "esp32s3/rom/spi_flash.h"
#if CONFIG_IDF_TARGET_ESP32C3
```
 may help the compiler...

**Comment by BrianPugh** [comment]
it looks like thats what spiffs is doing, are you able to test branches? I can push a branch with these fixes, but i don't have the devices.

**Comment by wreyford** [comment]
I dont know if that is do-able with the component manager. Can give it a
try by cloning it in the normal way.

**Comment by BrianPugh** [comment]
give #52 a try and lemme know how it goes.

**Comment by wreyford** [comment]
I cloned in the repository using:
```
git clone -b greater-device-compat https://github.com/joltwallet/esp_littlefs.git components/esp_littlefs
```
The directory tree looks ok.
It is unable to compile with message:
```
In file included from ../components/esp_littlefs/src/esp_littlefs.c:41:
../components/esp_littlefs/include/esp_littlefs.h:21:10: fatal error: littlefs/lfs.h: No such file or directory
 #include "littlefs/lfs.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
```
Full error log:
```
> Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .. <

-- Found Git: C:/esp/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
Solving dependencies requirements
Updating lock file at C:/ESP32/Projects/loadassist-s3\dependencies.lock
Processing 2 dependencies:
[1/2] idf (4.4.0)
[2/2] lvgl/lvgl (8.1.0)
-- Project sdkconfig file C:/ESP32/Projects/loadassist-s3/sdkconfig
warning: The int symbol LV_USE_FS_STDIO (defined at C:/ESP32/Projects/loadassist-s3/managed_components/lvgl__lvgl/Kconfig:788) is being evaluated in a logical context somewhere. It will always evaluate to n.
warning: The int symbol LV_USE_FS_POSIX (defined at C:/ESP32/Projects/loadassist-s3/managed_components/lvgl__lvgl/Kconfig:795) is being evaluated in a logical context somewhere. It will always evaluate to n.
warning: The int symbol LV_USE_FS_WIN32 (defined at C:/ESP32/Projects/loadassist-s3/managed_components/lvgl__lvgl/Kconfig:802) is being evaluated in a logical context somewhere. It will always evaluate to n.
Loading defaults file C:/ESP32/Projects/loadassist-s3/sdkconfig.defaults...
-- Found PythonInterp: C:/esp/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe (found version "3.8.7") 
-- Could NOT find Perl (missing: PERL_EXECUTABLE) 
-- App "loadassist" version: 47ca40a-dirty
-- Adding linker script C:/ESP32/Projects/loadassist-s3/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script C:/esp/esp-idf/components/esp_system/ld/esp32s3/sections.ld.in
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.version.ld
-- Adding linker script C:/esp/esp-idf/components/soc/esp32s3/ld/esp32s3.peripherals.ld
-- Components: app_trace app_update asio bootloader bootloader_support bt cbor cmock coap console cxx driver efuse escpos_printer esp-tls esp32s3 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_lcd esp_littlefs esp_local_ctrl esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test ieee802154 jsmn json libsodium log lvgl__lvgl lvgl_esp32_drivers lwip main mbedtls mdns mqtt newlib nghttp nvs_flash openssl openthread partition_table perfmon protobuf-c protocomm pthread sdmmc soc spi_flash spiffs tcp_transport tcpip_adapter tinyusb ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: C:/esp/esp-idf/components/app_trace C:/esp/esp-idf/components/app_update C:/esp/esp-idf/components/asio C:/esp/esp-idf/components/bootloader C:/esp/esp-idf/components/bootloader_support C:/esp/esp-idf/components/bt C:/esp/esp-idf/components/cbor 
C:/esp/esp-idf/components/cmock C:/esp/esp-idf/components/coap C:/esp/esp-idf/components/console C:/esp/esp-idf/components/cxx C:/esp/esp-idf/components/driver C:/esp/esp-idf/components/efuse C:/ESP32/Projects/loadassist-s3/components/escpos_printer C:/esp/esp-idf/components/esp-tls C:/esp/esp-idf/components/esp32s3 C:/esp/esp-idf/components/esp_adc_cal C:/esp/esp-idf/components/esp_common C:/esp/esp-idf/components/esp_eth C:/esp/esp-idf/components/esp_event C:/esp/esp-idf/components/esp_gdbstub C:/esp/esp-idf/components/esp_hid C:/esp/esp-idf/components/esp_http_client C:/esp/esp-idf/components/esp_http_server C:/esp/esp-idf/components/esp_https_ota C:/esp/esp-idf/components/esp_https_server C:/esp/esp-idf/components/esp_hw_support C:/esp/esp-idf/components/esp_ipc C:/esp/esp-idf/components/esp_lcd C:/ESP32/Projects/loadassist-s3/components/esp_littlefs C:/esp/esp-idf/components/esp_local_ctrl C:/esp/esp-idf/components/esp_netif C:/esp/esp-idf/components/esp_phy C:/esp/esp-idf/components/esp_pm C:/esp/esp-idf/components/esp_ringbuf C:/esp/esp-idf/components/esp_rom C:/esp/esp-idf/components/esp_serial_slave_link C:/esp/esp-idf/components/esp_system C:/esp/esp-idf/components/esp_timer C:/esp/esp-idf/components/esp_websocket_client C:/esp/esp-idf/components/esp_wifi C:/esp/esp-idf/components/espcoredump C:/esp/esp-idf/components/esptool_py C:/esp/esp-idf/components/expat C:/esp/esp-idf/components/fatfs C:/esp/esp-idf/components/freemodbus C:/esp/esp-idf/components/freertos C:/esp/esp-idf/components/hal C:/esp/esp-idf/components/heap C:/esp/esp-idf/components/idf_test C:/esp/esp-idf/components/ieee802154 C:/esp/esp-idf/components/jsmn C:/esp/esp-idf/components/json C:/esp/esp-idf/components/libsodium C:/esp/esp-idf/components/log C:/ESP32/Projects/loadassist-s3/managed_components/lvgl__lvgl C:/ESP32/Projects/loadassist-s3/components/lvgl_esp32_drivers C:/esp/esp-idf/components/lwip C:/ESP32/Projects/loadassist-s3/main C:/esp/esp-idf/components/mbedtls C:/esp/esp-idf/components/mdns C:/esp/esp-idf/components/mqtt C:/esp/esp-idf/components/newlib C:/esp/esp-idf/components/nghttp C:/esp/esp-idf/components/nvs_flash C:/esp/esp-idf/components/openssl C:/esp/esp-idf/components/openthread C:/esp/esp-idf/components/partition_table 
C:/esp/esp-idf/components/perfmon C:/esp/esp-idf/components/protobuf-c C:/esp/esp-idf/components/protocomm C:/esp/esp-idf/components/pthread C:/esp/esp-idf/components/sdmmc C:/esp/esp-idf/components/soc C:/esp/esp-idf/components/spi_flash C:/esp/esp-idf/components/spiffs C:/esp/esp-idf/components/tcp_transport C:/esp/esp-idf/components/tcpip_adapter C:/esp/esp-idf/components/tinyusb C:/esp/esp-idf/components/ulp C:/esp/esp-idf/components/unity C:/esp/esp-idf/components/usb C:/esp/esp-idf/components/vfs C:/esp/esp-idf/components/wear_levelling C:/esp/esp-idf/components/wifi_provisioning C:/esp/esp-idf/components/wpa_supplicant C:/esp/esp-idf/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ESP32/Projects/loadassist-s3/build

Terminal will be reused by tasks, press any key to close it.

> Executing task: cmake --build . <

[11/1247] Generating ../../partition_table/partition-table.bin
Partition table binary generated. Contents:
*******************************************************************************
# ESP-IDF Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,24K,
phy_init,data,phy,0xf000,4K,
factory,app,factory,0x10000,1M,
*******************************************************************************
[444/1247] Performing configure step for 'bootloader'
-- Found Git: C:/esp/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1")
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe    
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/esp/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
-- Project sdkconfig file C:/ESP32/Projects/loadassist-s3/sdkconfig
-- Adding linker script C:/esp/esp-idf/components/soc/esp32s3/ld/esp32s3.peripherals.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.api.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.libgcc.ld
-- Adding linker script C:/esp/esp-idf/components/esp_rom/esp32s3/ld/esp32s3.rom.newlib.ld
-- Adding linker script C:/esp/esp-idf/components/bootloader/subproject/main/ld/esp32s3/bootloader.ld
-- Adding linker script C:/esp/esp-idf/components/bootloader/subproject/main/ld/esp32s3/bootloader.rom.ld
-- Components: bootloader bootloader_support efuse esp32s3 esp_common esp_hw_support esp_rom esp_system esptool_py freertos hal log main micro-ecc newlib partition_table soc spi_flash xtensa
-- Component paths: C:/esp/esp-idf/components/bootloader C:/esp/esp-idf/components/bootloader_support C:/esp/esp-idf/components/efuse C:/esp/esp-idf/components/esp32s3 C:/esp/esp-idf/components/esp_common C:/esp/esp-idf/components/esp_hw_support C:/esp/esp-idf/components/esp_rom C:/esp/esp-idf/components/esp_system C:/esp/esp-idf/components/esptool_py C:/esp/esp-idf/components/freertos C:/esp/esp-idf/components/hal C:/esp/esp-idf/components/log C:/esp/esp-idf/components/bootloader/subproject/main C:/esp/esp-idf/components/bootloader/subproject/components/micro-ecc C:/esp/esp-idf/components/newlib C:/esp/esp-idf/components/partition_table C:/esp/esp-idf/components/soc C:/esp/esp-idf/components/spi_flash C:/esp/esp-idf/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ESP32/Projects/loadassist-s3/build/bootloader
[622/1247] Performing build step for 'bootloader'
[1/101] Generating project_elf_src_esp32s3.c
[2/101] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/mpu_hal.c.obj
[3/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/lldesc.c.obj
[4/101] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/cpu_hal.c.obj
[5/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/adc_periph.c.obj
[6/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/i2s_periph.c.obj
[7/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/soc_include_legacy_warn.c.obj
[8/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/interrupts.c.obj
[9/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/dedic_gpio_periph.c.obj
[10/101] Building C object esp-idf/hal/CMakeFiles/__idf_hal.dir/wdt_hal_iram.c.obj
[11/101] Building C object CMakeFiles/bootloader.elf.dir/project_elf_src_esp32s3.c.obj
[12/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/i2c_periph.c.obj
[13/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/gpio_periph.c.obj
[14/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/gdma_periph.c.obj
[15/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/lcd_periph.c.obj
[16/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/rmt_periph.c.obj
[17/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/ledc_periph.c.obj
[18/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/rtc_io_periph.c.obj
[19/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/pcnt_periph.c.obj
[20/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/mcpwm_periph.c.obj
[21/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/spi_periph.c.obj
[22/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/sdio_slave_periph.c.obj
[23/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/sigmadelta_periph.c.obj
[24/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/timer_periph.c.obj
[25/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/touch_sensor_periph.c.obj
[26/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/uart_periph.c.obj
[27/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/usb_periph.c.obj
[28/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/usb_phy_periph.c.obj
[29/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_clock_init.c.obj        
[30/101] Building C object esp-idf/soc/CMakeFiles/__idf_soc.dir/esp32s3/sdmmc_periph.c.obj
[31/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_mem.c.obj
[32/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_common.c.obj
[33/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_random_esp32s3.c.obj    
[34/101] Building C object esp-idf/spi_flash/CMakeFiles/__idf_spi_flash.dir/esp32s3/spi_flash_rom_patch.c.obj
[35/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_common_loader.c.obj     
[36/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_flash.c.obj
[37/101] Building C object esp-idf/micro-ecc/CMakeFiles/__idf_micro-ecc.dir/uECC_verify_antifault.c.obj
[38/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_encrypt.c.obj
[39/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_utility.c.obj
[40/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp_image_format.c.obj
[41/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_random.c.obj
[42/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_partitions.c.obj
[43/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/flash_qio_mode.c.obj
[44/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_efuse_esp32s3.c.obj     
[45/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/secure_boot.c.obj
[46/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_init.c.obj
[47/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_flash_config_esp32s3.c.obj
[48/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_console.c.obj
[49/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_clock_loader.c.obj      
[50/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_console_loader.c.obj    
[51/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32s3/esp_efuse_fields.c.obj
[52/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32s3/esp_efuse_table.c.obj
[53/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/bootloader_panic.c.obj
[54/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32s3/bootloader_soc.c.obj       
[55/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32s3/bootloader_sha.c.obj       
[56/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32s3/esp_efuse_rtc_calib.c.obj
[57/101] Building C object esp-idf/esp_system/CMakeFiles/__idf_esp_system.dir/esp_err.c.obj
[58/101] Building C object esp-idf/bootloader_support/CMakeFiles/__idf_bootloader_support.dir/src/esp32s3/bootloader_esp32s3.c.obj   
[59/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/esp32s3/esp_efuse_utility.c.obj
[60/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_fields.c.obj
[61/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/cpu_util.c.obj
[62/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_api.c.obj
[63/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_utility.c.obj
[64/101] Building C object esp-idf/efuse/CMakeFiles/__idf_efuse.dir/src/esp_efuse_api_key_esp32xx.c.obj
[65/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/compare_set.c.obj
[66/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_clk_init.c.obj
[67/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_clk.c.obj
[68/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_pm.c.obj
[69/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/chip_info.c.obj
[70/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_sleep.c.obj
[71/101] Building C object esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/eri.c.obj
[72/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_time.c.obj
[73/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_wdt.c.obj
[74/101] Building C object esp-idf/esp_hw_support/CMakeFiles/__idf_esp_hw_support.dir/port/esp32s3/rtc_init.c.obj
[75/101] Building C object esp-idf/xtensa/CMakeFiles/__idf_xtensa.dir/xt_trax.c.obj
[76/101] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_sys.c.obj
[77/101] Building C object esp-idf/esp_common/CMakeFiles/__idf_esp_common.dir/src/esp_err_to_name.c.obj
[78/101] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_crc.c.obj
[79/101] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_tjpgd.c.obj
[80/101] Building C object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_uart.c.obj
[81/101] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log_noos.c.obj
[82/101] Building ASM object esp-idf/esp_rom/CMakeFiles/__idf_esp_rom.dir/patches/esp_rom_longjmp.S.obj
[83/101] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log_buffers.c.obj
[84/101] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/bootloader_start.c.obj
[85/101] Building C object esp-idf/log/CMakeFiles/__idf_log.dir/log.c.obj
[86/101] Linking C static library esp-idf\log\liblog.a
[87/101] Linking C static library esp-idf\esp_rom\libesp_rom.a
[88/101] Linking C static library esp-idf\esp_common\libesp_common.a
[89/101] Linking C static library esp-idf\xtensa\libxtensa.a
[90/101] Linking C static library esp-idf\esp_hw_support\libesp_hw_support.a
[91/101] Linking C static library esp-idf\esp_system\libesp_system.a
[92/101] Linking C static library esp-idf\efuse\libefuse.a
[93/101] Linking C static library esp-idf\bootloader_support\libbootloader_support.a
[94/101] Linking C static library esp-idf\spi_flash\libspi_flash.a
[95/101] Linking C static library esp-idf\micro-ecc\libmicro-ecc.a
[96/101] Linking C static library esp-idf\soc\libsoc.a
[97/101] Linking C static library esp-idf\hal\libhal.a
[98/101] Linking C static library esp-idf\main\libmain.a
[99/101] Linking C executable bootloader.elf
[100/101] Generating binary image from built executable
esptool.py v3.2-dev
Merged 1 ELF section
Generated C:/ESP32/Projects/loadassist-s3/build/bootloader/bootloader.bin
[101/101] cmd.exe /C "cd /D C:\ESP32\Projects\loadassist-s3\build\bootloader\esp-idf\esptool_py && c:\esp\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x0 C:/ESP32/Projects/loadassist-s3/build/bootloader/bootloader.bin"
Bootloader binary size 0x4e80 bytes. 0x3180 bytes (39%) free.
[1027/1247] Building C object esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/esp_littlefs.c.obj
FAILED: esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/esp_littlefs.c.obj 
C:\esp\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe  -Iconfig -I../components/esp_littlefs/src -I../components/esp_littlefs/include -IC:/esp/esp-idf/components/newlib/platform_include -IC:/esp/esp-idf/components/freertos/include -IC:/esp/esp-idf/components/freertos/include/esp_additions/freertos -IC:/esp/esp-idf/components/freertos/port/xtensa/include -IC:/esp/esp-idf/components/freertos/include/esp_additions -IC:/esp/esp-idf/components/esp_hw_support/include -IC:/esp/esp-idf/components/esp_hw_support/include/soc -IC:/esp/esp-idf/components/esp_hw_support/include/soc/esp32s3 -IC:/esp/esp-idf/components/esp_hw_support/port/esp32s3/. -IC:/esp/esp-idf/components/esp_hw_support/port/esp32s3/private_include -IC:/esp/esp-idf/components/heap/include -IC:/esp/esp-idf/components/log/include -IC:/esp/esp-idf/components/lwip/include/apps -IC:/esp/esp-idf/components/lwip/include/apps/sntp -IC:/esp/esp-idf/components/lwip/lwip/src/include -IC:/esp/esp-idf/components/lwip/port/esp32/include -IC:/esp/esp-idf/components/lwip/port/esp32/include/arch -IC:/esp/esp-idf/components/soc/include -IC:/esp/esp-idf/components/soc/esp32s3/. -IC:/esp/esp-idf/components/soc/esp32s3/include -IC:/esp/esp-idf/components/hal/esp32s3/include -IC:/esp/esp-idf/components/hal/include -IC:/esp/esp-idf/components/hal/platform_port/include -IC:/esp/esp-idf/components/esp_rom/include -IC:/esp/esp-idf/components/esp_rom/include/esp32s3 -IC:/esp/esp-idf/components/esp_rom/esp32s3 -IC:/esp/esp-idf/components/esp_common/include -IC:/esp/esp-idf/components/esp_system/include -IC:/esp/esp-idf/components/esp_system/port/soc -IC:/esp/esp-idf/components/esp_system/port/public_compat -IC:/esp/esp-idf/components/xtensa/include -IC:/esp/esp-idf/components/xtensa/esp32s3/include -IC:/esp/esp-idf/components/driver/include -IC:/esp/esp-idf/components/driver/esp32s3/include -IC:/esp/esp-idf/components/esp_pm/include -IC:/esp/esp-idf/components/esp_ringbuf/include -IC:/esp/esp-idf/components/efuse/include -IC:/esp/esp-idf/components/efuse/esp32s3/include -IC:/esp/esp-idf/components/vfs/include -IC:/esp/esp-idf/components/esp_wifi/include -IC:/esp/esp-idf/components/esp_event/include -IC:/esp/esp-idf/components/esp_netif/include -IC:/esp/esp-idf/components/esp_eth/include -IC:/esp/esp-idf/components/tcpip_adapter/include -IC:/esp/esp-idf/components/esp_phy/include -IC:/esp/esp-idf/components/esp_phy/esp32s3/include -IC:/esp/esp-idf/components/esp_ipc/include -IC:/esp/esp-idf/components/app_trace/include -IC:/esp/esp-idf/components/esp_timer/include -IC:/esp/esp-idf/components/spi_flash/include -mlongcalls -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/ESP32/Projects/loadassist-s3=. -fmacro-prefix-map=C:/esp/esp-idf=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4-beta1-183-gf23dcd3555-dirt\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/esp_littlefs.c.obj -MF esp-idf\esp_littlefs\CMakeFiles\__idf_esp_littlefs.dir\src\esp_littlefs.c.obj.d -o esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/esp_littlefs.c.obj -c ../components/esp_littlefs/src/esp_littlefs.c
In file included from ../components/esp_littlefs/src/esp_littlefs.c:41:
../components/esp_littlefs/include/esp_littlefs.h:21:10: fatal error: littlefs/lfs.h: No such file or directory
 #include "littlefs/lfs.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
[1030/1247] Building C object esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/littlefs_api.c.obj
FAILED: esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/littlefs_api.c.obj
C:\esp\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin\xtensa-esp32s3-elf-gcc.exe  -Iconfig -I../components/esp_littlefs/src -I../components/esp_littlefs/include -IC:/esp/esp-idf/components/newlib/platform_include -IC:/esp/esp-idf/components/freertos/include -IC:/esp/esp-idf/components/freertos/include/esp_additions/freertos -IC:/esp/esp-idf/components/freertos/port/xtensa/include -IC:/esp/esp-idf/components/freertos/include/esp_additions -IC:/esp/esp-idf/components/esp_hw_support/include -IC:/esp/esp-idf/components/esp_hw_support/include/soc -IC:/esp/esp-idf/components/esp_hw_support/include/soc/esp32s3 -IC:/esp/esp-idf/components/esp_hw_support/port/esp32s3/. -IC:/esp/esp-idf/components/esp_hw_support/port/esp32s3/private_include -IC:/esp/esp-idf/components/heap/include -IC:/esp/esp-idf/components/log/include -IC:/esp/esp-idf/components/lwip/include/apps -IC:/esp/esp-idf/components/lwip/include/apps/sntp -IC:/esp/esp-idf/components/lwip/lwip/src/include -IC:/esp/esp-idf/components/lwip/port/esp32/include -IC:/esp/esp-idf/components/lwip/port/esp32/include/arch -IC:/esp/esp-idf/components/soc/include -IC:/esp/esp-idf/components/soc/esp32s3/. -IC:/esp/esp-idf/components/soc/esp32s3/include -IC:/esp/esp-idf/components/hal/esp32s3/include -IC:/esp/esp-idf/components/hal/include -IC:/esp/esp-idf/components/hal/platform_port/include -IC:/esp/esp-idf/components/esp_rom/include -IC:/esp/esp-idf/components/esp_rom/include/esp32s3 -IC:/esp/esp-idf/components/esp_rom/esp32s3 -IC:/esp/esp-idf/components/esp_common/include -IC:/esp/esp-idf/components/esp_system/include -IC:/esp/esp-idf/components/esp_system/port/soc -IC:/esp/esp-idf/components/esp_system/port/public_compat -IC:/esp/esp-idf/components/xtensa/include -IC:/esp/esp-idf/components/xtensa/esp32s3/include -IC:/esp/esp-idf/components/driver/include -IC:/esp/esp-idf/components/driver/esp32s3/include -IC:/esp/esp-idf/components/esp_pm/include -IC:/esp/esp-idf/components/esp_ringbuf/include -IC:/esp/esp-idf/components/efuse/include -IC:/esp/esp-idf/components/efuse/esp32s3/include -IC:/esp/esp-idf/components/vfs/include -IC:/esp/esp-idf/components/esp_wifi/include -IC:/esp/esp-idf/components/esp_event/include -IC:/esp/esp-idf/components/esp_netif/include -IC:/esp/esp-idf/components/esp_eth/include -IC:/esp/esp-idf/components/tcpip_adapter/include -IC:/esp/esp-idf/components/esp_phy/include -IC:/esp/esp-idf/components/esp_phy/esp32s3/include -IC:/esp/esp-idf/components/esp_ipc/include -IC:/esp/esp-idf/components/app_trace/include -IC:/esp/esp-idf/components/esp_timer/include -IC:/esp/esp-idf/components/spi_flash/include -mlongcalls -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/ESP32/Projects/loadassist-s3=. -fmacro-prefix-map=C:/esp/esp-idf=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4-beta1-183-gf23dcd3555-dirt\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/littlefs_api.c.obj -MF esp-idf\esp_littlefs\CMakeFiles\__idf_esp_littlefs.dir\src\littlefs_api.c.obj.d -o esp-idf/esp_littlefs/CMakeFiles/__idf_esp_littlefs.dir/src/littlefs_api.c.obj -c ../components/esp_littlefs/src/littlefs_api.c
../components/esp_littlefs/src/littlefs_api.c:12:10: fatal error: littlefs/lfs.h: No such file or directory
 #include "littlefs/lfs.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
[1036/1247] Building C object esp-idf/lvgl__lvgl/CMakeFiles/__idf_lvgl__lvgl.dir/src/core/lv_indev_scroll.c.obj
ninja: build stopped: subcommand failed.
The terminal process "C:\Program Files\PowerShell\7\pwsh.exe -Command cmake --build ." terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by BrianPugh** [comment]
whenever you directly clone, you have to pass in the `--recursive` flag, so:
```
git clone -b greater-device-compat --recursive https://github.com/joltwallet/esp_littlefs.git components/esp_littlefs
```

Or, in an already cloned repo, the command to initialize/pull/checkout all the appropriate submodules is:
```
git submodule update --init --recursive
```

**Comment by wreyford** [comment]
Awesome, thanks!

**Comment by BrianPugh** [comment]
please lemme know if it works for you!

**Comment by wreyford** [comment]
Thx a lot @BrianPugh,
The code compiles perfectly for the S3 build. I have sent the binary off to our hardware guy, and he will test his side.
I'm sure all should be fine.
Are you going to push the #define updates to your component, as I would prefer to use LittleFS as a component.

**Comment by jrgilman** [comment]
> alright @wreyford , I think I fixed it. I updated the CI so that it recursively checks out submodule when building the tarball for the IDF component manager. I also bumped the version so there's now v1.0.1. I downloaded the tar from the official website and the files are there now, so hopefully this fixes your issue (lemme know!). Thanks for noticing and reporting this.

This just saved my butt, I had the exact same issue as @wreyford described. Should the README be updated to say to use 1.0.1? I can submit a PR if necessary.

**Comment by wreyford** [comment]
@BrianPugh I confirm that LittleFs not only compiles for S3 but our preliminary tests indicate thst it is working as expected.
Thx a lot.

**Comment by BrianPugh** [comment]
I released version 1.1.0 with these added devices. @jrgilman I updated the README.
